### PR TITLE
Fix VinCommand, android not contain DatatypeConverter class. 

### PR DESCRIPTION
**Pull request by valens254**
Added IgnitionMonitorCommand.  Android don't contains DatatypeConverter class.

### CODE REVIEW

**Comment by pires** [comment]
I actually looked for this one but the code compiled. Weird. My bad.

**Comment by valens254** [comment]
Sorry, I've recently been using Git and forgot to make the merger

**Comment by pires** [comment]
This branch needs rebase.

**Comment by valens254** [comment]
Now I already rebase  this branch

**Comment by pires** [comment]
Github disagrees.

**Comment by valens254** [comment]
Do I need to make a new pull request?

**Comment by pires** [comment]
No, I'll take it from here.

**Comment by valens254** [comment]
I do rebase after pull request, sorry.

**Pull request merged**
