### PR TITLE
Update FuelTrim.java

### PR DESCRIPTION
**Pull request by Pho3niX90**

### CODE REVIEW

**Comment by Pho3niX90** [comment]
I cannot see how this command ever worked for anyone. Unless you have a dongle that automatically corrects the commands send without the leading 0's it would have never worked. 

After making the change it is working on the 20 cars I am actively testing this on.

**Comment by Dechcaudron** [comment]
I'm probably wrong, but wouldn't don't all trim commands range from 14 to 1B? If so, why do we use a 0 as the first command character (not talking about the mode characters)

**Comment by Pho3niX90** [comment]
@Dechcaudron 
You are thinking about these 
image
They aren't used in the library, these are used.
image


Previously it was sending the commands incorrect like the following:
01 6
01 7
01 8
01 9

**Comment by Dechcaudron** [comment]
You are right, sorry about the misunderstanding. This is an important fix.

**Pull request merged**
