### PR TITLE
Fixed not using the delay

### PR DESCRIPTION
**Pull request by stealthcopter**
I've added in a sleep so that the ObdCommand class works as I *think* it was intended (I'm new to obd2 stuff so may be wrong). I haven't added tests yet as I'm unfamiliar with the testing framework, but I expect it would look something like the following?

```
    private int TEST_DELAY_MILLIS = 2000;

    /**
     * @throws Exception
     */
    @BeforeMethod
    public void setUp() throws Exception {
        command = new SpeedCommand();
        command.setResponseTimeDelay(TEST_DELAY_MILLIS);
    }

    /**
     * Test for valid InputStream read, 64km/h
     *
     * @throws IOException
     */
    @Test
    public void testValidSpeedMetric() throws IOException {
        
        OutputStream mockOut = createMock(OutputStream.class);
        
        long startTime = System.currentTimeMillis();
        
        command.sendCommand(mockOut);
        
        long timeTaken = System.currentTimeMillis() - startTime;

        boolean timeGreaterThanDelay = timeTaken > TEST_DELAY_MILLIS;

        assertEquals(timeGreaterThanDelay, true);
    }
```

If this is stupid or there is a better way, please let me know :)

### CODE REVIEW

**Comment by pires** [comment]
The problem with this PR is that it forces a response delay, even if the never used default of 200ms. I suggest the following:

```java

private boolean responseDelayEnabled = false;
private Long responseDelayInMs = null;

public void setResponseTimeDelay(Long ms){
    if (ms == null) {
        this.responseDelayEnabled = false;
    } else {
         this.responseDelayEnabled = true;
    }
    this.responseDelayInMs = ms;
}

protected void sendCommand(...) {
    (...)
    if (responseDelayEnabled && responseDelayInMs != null && responseDelayInMs > 0) {
        Thread.sleep(responseDelayInMs);
    }
}

// same applies to resendCommand(...)
```

Here's the explanation:
* Replace `responseTimeDelay` with `Long responseDelayInMs` and begone with its default value
* `command.setResponseTimeDelay(TEST_DELAY_MILLIS);` enables behavior like  `if responseTimeDelay was set, then use it` - since in Android, Java 8 `Optional<T>` is not supported, I think one can do with a `boolean responseDelayEnabled` and a `long responseDelayInMs`.

One test failing but is not related to this PR changes.

**Comment by stealthcopter** [comment]
Yes, good point, didn't consider this would actually slow everyone down! I agree with changes, however would the boolean responseDelayEnabled be superfluous if we are using Long instead of a primitive, so we could just simplify it to:

```
private Long responseDelayInMs = null;

public void setResponseTimeDelay(Long ms){
    this.responseDelayInMs = ms;
}

protected void sendCommand(...) {
    (...)
    if (responseDelayInMs != null && responseDelayInMs > 0) {
        Thread.sleep(responseDelayInMs);
    }
}

```

It could be simplified even further, as responseDelayInMs would be cast to 0 if null but makes the code less understandable then I think.

**Comment by pires** [comment]
I am good with dropping the boolean for as long as the code deals properly with nullable `responseDelayInMs`. I am not OK with comparing `responseDelayInMs` wrapped value alone.

**Comment by stealthcopter** [comment]
@pires Does that look right?

**Comment by pires** [comment]
:+1: thanks a lot @stealthcopter!

**Comment by stealthcopter** [comment]
No problem, thanks for an awesome library :)

**Pull request merged**
