### PR TITLE
AvailablePids with range

### PR DESCRIPTION
**Pull request by Dechcaudron**
Done with the feature. I also took the freedom to remove the first 4 bytes of the return the sequence as they simply echo the command code.

### CODE REVIEW

**Comment by pires** [comment]
@Dechcaudron thanks. Can you squash your commits into a single one?

**Comment by Dechcaudron** [comment]
How can I do that?

**Comment by pires** [comment]
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Dechcaudron** [comment]
I'll do it myself in a couple days. I'm having trouble right now understanding details about rebase and I can't spare the time.

**Pull request closed without merging**
