### PR TITLE
Update PendingTroubleCodesCommand.java

### PR DESCRIPTION
**Pull request by Pho3niX90**
Quick fix to resolve following error:
rawData: 43010301030000
Exception: length=14; regionStart=13; regionLength=3

### CODE REVIEW

**Comment by pires** [comment]
@Pho3niX90 this [breaks tests](https://circleci.com/gh/pires/obd-java-api/26). Care to fix?

**Comment by Pho3niX90** [comment]
@pirees yes I saw. Let me do some more debugging. I am not convinced this class yields accurate results. I am getting codes that aren't stored (test system). In fact theres no codes but returning 3.

**Comment by Pho3niX90** [comment]
Should be fixed now. My test also proves fruitful

**Comment by pires** [comment]
Care to squash your commits into one?

**Comment by Pho3niX90** [comment]
@pires I made the changes via browser. I am not sure if there is a way to rebase via web interface?

**Comment by pires** [comment]
No there is not. Still #108 blocks this PR from being merged, right?

**Comment by Pho3niX90** [comment]
Yes. Hold for the other change

**Comment by pires** [comment]
Ready to merge? I will squash the commits and edit the commit message.

**Comment by Pho3niX90** [comment]
Yes please.

**Pull request closed without merging**
